Failure # 1 (occurred at 2024-12-11_20-00-15)
[36mray::ImplicitFunc.train()[39m (pid=1314083, ip=172.24.11.109, actor_id=2e0214dda1a7127299db416601000000, repr=train)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, '#'.

The above exception was the direct cause of the following exception:

[36mray::ImplicitFunc.train()[39m (pid=1314083, ip=172.24.11.109, actor_id=2e0214dda1a7127299db416601000000, repr=train)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/digvijay/Documents/developer/greedy_kernel_alignment/kgreedy/lib/python3.12/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/home/digvijay/Documents/developer/greedy_kernel_alignment/kgreedy/lib/python3.12/site-packages/ray/air/_internal/util.py", line 104, in run
    self._ret = self._target(*self._args, **self._kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/digvijay/Documents/developer/greedy_kernel_alignment/kgreedy/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/digvijay/Documents/developer/greedy_kernel_alignment/kgreedy/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py", line 250, in _trainable_func
    output = fn()
             ^^^^
  File "/home/digvijay/Documents/developer/greedy_kernel_alignment/main.py", line 39, in train
    features, target = data_generator.generate_dataset()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/digvijay/Documents/developer/greedy_kernel_alignment/utils/data_generator.py", line 29, in generate_dataset
    return self.load_from_file()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/digvijay/Documents/developer/greedy_kernel_alignment/utils/data_generator.py", line 108, in load_from_file
    data = np.load(self.file_path, allow_pickle=True).item()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/digvijay/Documents/developer/greedy_kernel_alignment/kgreedy/lib/python3.12/site-packages/numpy/lib/npyio.py", line 467, in load
    raise pickle.UnpicklingError(
_pickle.UnpicklingError: Failed to interpret file '/home/digvijay/Documents/developer/greedy_kernel_alignment/configs/ccka/corners.yaml' as a pickle
